(part "TPS62827ADMQR"
    (packageRef "TPS62827ADMQR")
    (interface
        (port "1" (symbPinId 1) (portName "EN") (portType INOUT))
        (port "2" (symbPinId 2) (portName "PG") (portType INOUT))
        (port "3" (symbPinId 3) (portName "FB") (portType INOUT))
        (port "4" (symbPinId 4) (portName "GND") (portType INOUT))
        (port "5" (symbPinId 5) (portName "SW") (portType INOUT))
        (port "6" (symbPinId 6) (portName "VIN") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "101")
    (property "Mouser_Part_Number" "595-TPS62827ADMQR")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Texas-Instruments/TPS62827ADMQR?qs=DRkmTr78QATCWGi3%2FWmmPQ%3D%3D")
    (property "Manufacturer_Name" "Texas Instruments")
    (property "Manufacturer_Part_Number" "TPS62827ADMQR")
    (property "Description" "Step Down DC DC Converter")
    (property "Datasheet_Link" "")
    (property "symbolName1" "TPS62827ADMQR")
)
